"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { ChevronDown, Search, MessageCircle, HelpCircle, Sparkles, ArrowRight } from 'lucide-react';
import Link from "next/link";
import { useTranslations } from "next-intl";
import { cn } from "@/lib/utils";
import { Reveal } from "@/components/Reveal";
type faqItems = any;
const faqItems: any = [];
import { fadeInUp, staggerContainer } from "@/lib/motion";

const FAQ_CATEGORIES = [
  {
    key: "general",
    label: "General",
    icon: HelpCircle,
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-200",
    items: [
      {
        question: "What is Builder by HotCode?",
        answer:
          "Builder by HotCode is an AI-powered website generator that turns a plain-text description of your idea into a fully functional, production-ready website in under 60 seconds. It uses GPT-4o to write clean Next.js + TypeScript code, complete with styling and responsive layouts.",
      },
      {
        question: "Who is Builder designed for?",
        answer:
          "Builder is designed for founders, designers, developers, and anyone who wants to ship a website fast. Whether you need a landing page, a portfolio, a SaaS marketing site, or a full-stack app shell, Builder handles the heavy lifting so you can focus on your product.",
      },
      {
        question: "Do I need to know how to code?",
        answer:
          "Not at all. You describe what you want in plain English and Builder generates the complete codebase. If you do know how to code, you can download the source and customize it however you like.",
      },
      {
        question: "What kind of websites can I build?",
        answer:
          "Landing pages, portfolios, SaaS marketing sites, e-commerce storefronts, dashboards, blogs, documentation sites, and more. If you can describe it, Builder can generate it.",
      },
    ],
  },
  {
    key: "pricing",
    label: "Pricing",
    icon: Sparkles,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    items: [
      {
        question: "How does the credit system work?",
        answer:
          "Each website generation consumes one credit from your account balance. You can purchase credit packs starting from our Free tier (50 credits at no cost) up to our 500-credit Pro pack. Credits never expire, so you can use them at your own pace.",
      },
      {
        question: "Is there a free plan?",
        answer:
          "Yes. Every new account starts with 50 free credits — no credit card required. That gives you 50 full website generations to explore what Builder can do before you decide to top up.",
      },
      {
        question: "Do credits expire?",
        answer:
          "No. Credits you purchase never expire. Free monthly credits refresh on the first of each month, but any purchased credits roll over indefinitely.",
      },
      {
        question: "Can I get a refund?",
        answer:
          "If you are unsatisfied with your purchase, contact us within 7 days and we will review your case. Refunds are issued at our discretion for unused credits.",
      },
      {
        question: "Are there any hidden fees or subscriptions?",
        answer:
          "No subscriptions, no hidden fees. You pay once for a credit pack and use those credits whenever you want. The Free tier renews automatically each month at no cost.",
      },
    ],
  },
  {
    key: "technical",
    label: "Technical",
    icon: MessageCircle,
    color: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-200",
    items: [
      {
        question: "What does 'production-ready' actually mean?",
        answer:
          "Every site Builder generates is written in Next.js 14 with TypeScript and Tailwind CSS — the same stack used by professional development teams. The output is clean, well-structured, and ready to deploy without modification.",
      },
      {
        question: "What tech stack does Builder use?",
        answer:
          "Builder generates Next.js 14 (App Router) projects with TypeScript, Tailwind CSS, and lucide-react icons. The output follows modern best practices including server components, proper file structure, and accessibility standards.",
      },
      {
        question: "How accurate is the AI generation?",
        answer:
          "Builder uses GPT-4o, one of the most capable models available. For most prompts, the first generation is 80-95% of what you need. You can refine with follow-up prompts or edit the downloaded source code directly.",
      },
      {
        question: "Can I use the generated code commercially?",
        answer:
          "Yes. All code generated by Builder is yours to use however you like, including in commercial projects. There are no royalties, attribution requirements, or licensing restrictions.",
      },
    ],
  },
  {
    key: "export",
    label: "Export & Deploy",
    icon: ArrowRight,
    color: "text-orange-600",
    bg: "bg-orange-50",
    border: "border-orange-200",
    items: [
      {
        question: "How do I export my website?",
        answer:
          "From the live preview, click the Export button to download a ZIP file containing the complete Next.js project. On Starter plans and above, you can also push directly to a GitHub repository with one click.",
      },
      {
        question: "Where can I deploy my generated site?",
        answer:
          "Anywhere that supports Next.js: Vercel, Netlify, Railway, Render, AWS Amplify, or your own server. The generated project includes a standard package.json so deployment is straightforward on any platform.",
      },
      {
        question: "Can I edit the code after downloading?",
        answer:
          "Absolutely. The downloaded ZIP is a standard Next.js project. Open it in VS Code, run npm install, and start editing. It is your code — no lock-in, no proprietary formats.",
      },
      {
        question: "Does Builder support GitHub integration?",
        answer:
          "Yes, on Starter plans and above. Connect your GitHub account and push generated projects directly to a new or existing repository with a single click.",
      },
      {
        question: "Can I deploy to a custom domain?",
        answer:
          "Custom domain deployment is available on the Pro plan. We handle the DNS configuration and SSL certificate so your site is live on your own domain in minutes.",
      },
    ],
  },
];

function AccordionItem({
  question,
  answer,
  isOpen,
  onToggle,
}: {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="border-b border-gray-100 last:border-0">
      <button
        onClick={onToggle}
        className="flex w-full items-start justify-between gap-4 py-5 text-left transition-colors hover:text-[var(--primary)]"
        aria-expanded={isOpen}
      >
        <span className="font-medium text-gray-900 leading-snug">{question}</span>
        <ChevronDown
          className={cn(
            "mt-0.5 h-5 w-5 flex-shrink-0 text-gray-400 transition-transform duration-300",
            isOpen && "rotate-180 text-[var(--primary)]"
          )}
          aria-hidden="true"
        />
      </button>
      <motion.div
        initial={false}
        animate={{ height: isOpen ? "auto" : 0, opacity: isOpen ? 1 : 0 }}
        transition={{ duration: 0.3, ease: "easeOut" }}
        className="overflow-hidden"
      >
        <p className="pb-5 text-sm leading-relaxed text-gray-600">{answer}</p>
      </motion.div>
    </div>
  );
}

function CategorySection({
  category,
  searchQuery,
}: {
  category: (typeof FAQ_CATEGORIES)[number];
  searchQuery: string;
}) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const Icon = category.icon;

  const filtered = category.items.filter(
    (item) =>
      searchQuery === "" ||
      item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchQuery.toLowerCase())
  );

  if (filtered.length === 0) return null;

  return (
    <Reveal>
      <div className="mb-10">
        <div className="mb-4 flex items-center gap-3">
          <div className={cn("flex h-9 w-9 items-center justify-center rounded-xl", category.bg)}>
            <Icon className={cn("h-4 w-4", category.color)} aria-hidden="true" />
          </div>
          <h2 className="text-lg font-semibold text-gray-900">{category.label}</h2>
          <span className="ml-auto rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-500">
            {filtered.length}
          </span>
        </div>
        <div className="rounded-2xl border border-gray-100 bg-white shadow-[0_1px_2px_rgba(0,0,0,0.04),0_8px_24px_-8px_rgba(0,0,0,0.08)] px-6">
          {filtered.map((item, i) => (
            <AccordionItem
              key={item.question}
              question={item.question}
              answer={item.answer}
              isOpen={openIndex === i}
              onToggle={() => setOpenIndex(openIndex === i ? null : i)}
            />
          ))}
        </div>
      </div>
    </Reveal>
  );
}

export default function FAQPage() {
  const t = useTranslations();
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState<string>("all");

  const totalQuestions = FAQ_CATEGORIES.reduce((sum, cat) => sum + cat.items.length, 0);

  const filteredCategories =
    activeCategory === "all"
      ? FAQ_CATEGORIES
      : FAQ_CATEGORIES.filter((cat) => cat.key === activeCategory);

  const hasResults = filteredCategories.some((cat) =>
    cat.items.some(
      (item) =>
        searchQuery === "" ||
        item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.answer.toLowerCase().includes(searchQuery.toLowerCase())
    )
  );

  return (
    <main className="min-h-screen bg-[#f7f7fb]">
      {/* Hero */}
      <Reveal>
        <section className="relative overflow-hidden bg-gradient-to-b from-violet-50 via-[#f0eeff] to-[#f7f7fb] px-4 pb-16 pt-20 text-center">
          <div
            className="pointer-events-none absolute inset-0 opacity-30"
            style={{
              backgroundImage:
                "radial-gradient(circle at 20% 50%, rgba(139,92,246,0.15) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(99,102,241,0.1) 0%, transparent 50%)",
            }}
            aria-hidden="true"
          />
          <motion.div
            variants={staggerContainer}
            initial="hidden"
            animate="visible"
            className="relative mx-auto max-w-2xl"
          >
            <motion.div variants={fadeInUp} className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white/80 px-4 py-1.5 text-sm font-medium text-violet-700 shadow-sm backdrop-blur-sm">
              <HelpCircle className="h-3.5 w-3.5" aria-hidden="true" />
              {t("faq.badge")}
            </motion.div>
            <motion.h1
              variants={fadeInUp}
              className="mb-4 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl"
            >
              {t("faq.heading")}
            </motion.h1>
            <motion.p variants={fadeInUp} className="mb-8 text-lg leading-relaxed text-gray-500">
              {t("faq.subheading")}
            </motion.p>
            {/* Search */}
            <motion.div variants={fadeInUp} className="relative mx-auto max-w-lg">
              <Search
                className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400"
                aria-hidden="true"
              />
              <input
                type="search"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={t("faq.searchPlaceholder")}
                className="w-full rounded-xl border border-gray-200 bg-white py-3 pl-11 pr-4 text-sm text-gray-900 shadow-sm outline-none transition placeholder:text-gray-400 focus:border-violet-400 focus:ring-2 focus:ring-violet-100"
                aria-label={t("faq.searchPlaceholder")}
              />
            </motion.div>
            <motion.p variants={fadeInUp} className="mt-4 text-sm text-gray-400">
              {t("faq.totalCount", { count: totalQuestions })}
            </motion.p>
          </motion.div>
        </section>
      </Reveal>

      {/* Category Filter */}
      <Reveal>
        <section className="sticky top-0 z-10 border-b border-gray-100 bg-white/90 px-4 py-3 backdrop-blur-md">
          <div className="mx-auto flex max-w-3xl items-center gap-2 overflow-x-auto pb-0.5">
            <button
              onClick={() => setActiveCategory("all")}
              className={cn(
                "flex-shrink-0 rounded-full px-4 py-1.5 text-sm font-medium transition-all",
                activeCategory === "all"
                  ? "bg-[var(--primary)] text-white shadow-sm"
                  : "bg-gray-100 text-gray-600 hover:bg-gray-200"
              )}
            >
              {t("faq.filterAll")}
            </button>
            {FAQ_CATEGORIES.map((cat) => {
              const Icon = cat.icon;
              return (
                <button
                  key={cat.key}
                  onClick={() => setActiveCategory(cat.key)}
                  className={cn(
                    "flex flex-shrink-0 items-center gap-1.5 rounded-full px-4 py-1.5 text-sm font-medium transition-all",
                    activeCategory === cat.key
                      ? "bg-[var(--primary)] text-white shadow-sm"
                      : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                  )}
                >
                  <Icon className="h-3.5 w-3.5" aria-hidden="true" />
                  {cat.label}
                </button>
              );
            })}
          </div>
        </section>
      </Reveal>

      {/* FAQ Accordion */}
      <section className="mx-auto max-w-3xl px-4 py-14">
        {hasResults ? (
          filteredCategories.map((cat) => (
            <CategorySection key={cat.key} category={cat} searchQuery={searchQuery} />
          ))
        ) : (
          <Reveal>
            <div className="py-20 text-center">
              <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gray-100">
                <Search className="h-7 w-7 text-gray-400" aria-hidden="true" />
              </div>
              <h3 className="mb-2 text-lg font-semibold text-gray-900">{t("faq.noResults")}</h3>
              <p className="text-sm text-gray-500">{t("faq.noResultsHint")}</p>
              <button
                onClick={() => {
                  setSearchQuery("");
                  setActiveCategory("all");
                }}
                className="mt-4 rounded-lg bg-[var(--primary)] px-5 py-2 text-sm font-medium text-white transition hover:opacity-90"
              >
                {t("faq.clearSearch")}
              </button>
            </div>
          </Reveal>
        )}
      </section>

      {/* Contact CTA */}
      <Reveal>
        <section className="px-4 pb-20">
          <div className="mx-auto max-w-3xl overflow-hidden rounded-3xl bg-gradient-to-br from-violet-600 to-indigo-700 p-10 text-center shadow-[0_8px_40px_-8px_rgba(109,40,217,0.4)]">
            <div
              className="pointer-events-none absolute inset-0 opacity-20"
              style={{
                backgroundImage:
                  "radial-gradient(circle at 30% 70%, rgba(255,255,255,0.15) 0%, transparent 60%)",
              }}
              aria-hidden="true"
            />
            <div className="relative">
              <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-1.5 text-sm font-medium text-white/90 backdrop-blur-sm">
                <MessageCircle className="h-3.5 w-3.5" aria-hidden="true" />
                {t("faq.ctaBadge")}
              </div>
              <h2 className="mb-3 text-3xl font-bold text-white">{t("faq.ctaHeading")}</h2>
              <p className="mb-8 text-base leading-relaxed text-white/75">{t("faq.ctaSubheading")}</p>
              <div className="flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Link
                  href="/contact"
                  className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 text-sm font-semibold text-violet-700 shadow-sm transition hover:bg-violet-50"
                >
                  {t("faq.ctaContact")}
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
                <Link
                  href="/generate"
                  className="inline-flex items-center gap-2 rounded-xl border border-white/30 bg-white/10 px-6 py-3 text-sm font-semibold text-white backdrop-blur-sm transition hover:bg-white/20"
                >
                  {t("faq.ctaGenerate")}
                </Link>
              </div>
            </div>
          </div>
        </section>
      </Reveal>
    </main>
  );
}